version: "3.3"
services:
  umb:
    image: "rightway/php:7.1-debug"
    ports:
      - "${UMB_HTTP_PORT}:80"
      - "${UMB_SSH_PORT}:22"
    volumes:
      - './config/nginx/conf.d:/etc/nginx/conf.d'
      - './config/php:/etc/php/app_conf'
    environment:
      PHP_INI_SCAN_DIR: ':/etc/php/app_conf'
      APP_USER_ID: ${HOST_USER_UID}
      APP_GROUP_ID: ${HOST_USER_GID}